[project]
authors = ["Modular <hello@modular.com>"]
channels = ["https://conda.modular.com/max-nightly", "https://conda.modular.com/max", "https://repo.prefix.dev/modular-community", "conda-forge"]
name = "mojo-gpu-puzzles"
platforms = ["linux-64", "osx-arm64"]
version = "0.0.0"

[tasks]
format = "mojo format problems solutions"

tests = { cmd = "bash solutions/run.sh" }

build-book = "cd book && mdbook build"
book = { cmd = "cd book && mdbook serve --open", depends-on = ["build-book"] }
clean = { cmd = "cd book && mdbook clean" }

p01 = "mojo problems/p01/p01.mojo"
viz01 = "cd book/src/puzzle_01 && python puzzle_01_viz.py"

p02 = "mojo problems/p02/p02.mojo"
viz02 = "cd book/src/puzzle_02 && python puzzle_02_viz.py"

p03 = "mojo problems/p03/p03.mojo"
viz03 = "cd book/src/puzzle_03 && python puzzle_03_viz.py"

p04 = "mojo problems/p04/p04.mojo"
p04_layout_tensor = "mojo problems/p04/p04_layout_tensor.mojo"
viz04 = "cd book/src/puzzle_04 && python puzzle_04_viz.py"
thread_indexing = "cd book/src/puzzle_04 && python thread_indexing_viz.py"
layout_tensor_intro = "mojo book/src/puzzle_04/intro.mojo"

p05 = "mojo problems/p05/p05.mojo"
p05_layout_tensor = "mojo problems/p05/p05_layout_tensor.mojo"
viz05 = "cd book/src/puzzle_05 && python puzzle_05_viz.py"

p06 = "mojo problems/p06/p06.mojo"
viz06 = "cd book/src/puzzle_06 && python puzzle_06_viz.py"

p07 = "mojo problems/p07/p07.mojo"
p07_layout_tensor = "mojo problems/p07/p07_layout_tensor.mojo"
viz07 = "cd book/src/puzzle_07 && python puzzle_07_viz.py"

p08 = "mojo problems/p08/p08.mojo"
p08_layout_tensor = "mojo problems/p08/p08_layout_tensor.mojo"
viz08 = "cd book/src/puzzle_08 && python puzzle_08_viz.py"

p09 = "mojo problems/p09/p09.mojo"
p09_layout_tensor = "mojo problems/p09/p09_layout_tensor.mojo"
viz09 = "cd book/src/puzzle_09 && python puzzle_09_viz.py"

p10 = "mojo problems/p10/p10.mojo"
p10_layout_tensor = "mojo problems/p10/p10_layout_tensor.mojo"
viz10 = "cd book/src/puzzle_10 && python puzzle_10_viz.py"

p11 = "mojo problems/p11/p11.mojo"
viz11 = "cd book/src/puzzle_11 && python puzzle_11_viz.py"

p12 = "mojo problems/p12/p12.mojo"
viz12 = "cd book/src/puzzle_12 && python puzzle_12_viz.py"

p13 = "mojo problems/p13/p13.mojo"
viz13 = "cd book/src/puzzle_13 && python puzzle_13_viz.py"

p14 = "mojo problems/p14/p14.mojo"
viz14 = "cd book/src/puzzle_14 && python puzzle_14_viz.py"

p15 = "cd problems/p15 && mojo package op -o op.mojopkg && python p15.py"

[dependencies]
max = "*"
bash = ">=5.2.21,<6"
python = "==3.12"
manim = ">=0.18.1,<0.19"
mdbook = ">=0.4.48,<0.5"
